create table STUDENT ( id NUMBER GENERATED BY DEFAULT AS IDENTITY, name varchar2(50));
INSERT INTO STUDENT (id, name) VALUES (1, 'Ajay');
INSERT INTO STUDENT (id, name) VALUES (2, 'Vijay');
INSERT INTO STUDENT (id, name) VALUES (3, 'James');
INSERT INTO STUDENT (id, name) VALUES (4, 'Duke');
INSERT INTO STUDENT (id, name) VALUES (5, 'Marry');